import "./styles/base.css";
import "./styles/components.css";
import "./styles/admin.css";
import { route, initRouter } from "./router.js";
import { initializeAuth, onAuthChange } from "./services/auth.js";
import { trackPageView } from "./services/analytics.js";
import { initializeBackgroundMusic } from "./services/background-music.js";
import { updateNav } from "./components/app-shell.js";
import { renderHome } from "./pages/home.js";
import { renderBrowse, renderCategory } from "./pages/browse.js";
import { renderDetail } from "./pages/detail.js";
import { renderSearch } from "./pages/search.js";
import { renderFavorites } from "./pages/favorites.js";
import { renderAuth } from "./pages/auth.js";
import { renderProfile } from "./pages/profile.js";
import { renderAdminLogin } from "./pages/admin/login.js";
import { renderAdminDashboard } from "./pages/admin/dashboard.js";
import { renderAdminPoems } from "./pages/admin/poems.js";
import { renderAdminPoemEditor } from "./pages/admin/poem-editor.js";
import { renderAdminUsers } from "./pages/admin/users.js";
import { renderAdminUserEditor } from "./pages/admin/user-editor.js";
route("/", renderHome);
route("/browse", renderBrowse);
route("/browse/:category", renderCategory);
route("/poem/:id", renderDetail);
route("/search", renderSearch);
route("/favorites", renderFavorites);
route("/auth", renderAuth);
route("/profile", renderProfile);
route("/admin", () => { window.location.hash = "#/admin/dashboard"; });
route("/admin/login", renderAdminLogin);
route("/admin/dashboard", renderAdminDashboard);
route("/admin/poems", renderAdminPoems);
route("/admin/poems/:id", renderAdminPoemEditor);
route("/admin/users", renderAdminUsers);
route("/admin/users/:id", renderAdminUserEditor);

await initializeAuth();
initializeBackgroundMusic();
onAuthChange(() => updateNav());
window.addEventListener("hashchange", () => { const path = window.location.hash.slice(1) || "/"; setTimeout(() => trackPageView(path), 0); });
initRouter();
setTimeout(() => trackPageView(window.location.hash.slice(1) || "/"), 0);