-- 诗三百：后台管理、诗篇数据与匿名访问统计
create table if not exists public.poems (
  id integer generated by default as identity primary key,
  slug text unique,
  title text not null,
  chapter text not null,
  section text not null,
  content jsonb not null default '[]'::jsonb,
  annotation text,
  translation text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.poems add column if not exists slug text;
alter table public.poems add column if not exists sort_order integer not null default 0;
alter table public.poems add column if not exists is_published boolean not null default true;
alter table public.poems add column if not exists created_at timestamptz not null default now();
alter table public.poems add column if not exists updated_at timestamptz not null default now();
update public.poems set slug = 'poem-' || id where slug is null or slug = '';
create unique index if not exists poems_slug_unique_idx on public.poems(slug);
create index if not exists poems_public_order_idx on public.poems(is_published, sort_order, id);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null,
  avatar_url text,
  bio text,
  status smallint not null default 1 check (status in (0, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  poem_id integer not null references public.poems(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, poem_id)
);
create index if not exists favorites_user_created_idx on public.favorites(user_id, created_at desc);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.user_profiles(id, nickname)
  values (new.id, coalesce(nullif(new.raw_user_meta_data->>'nickname', ''), split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin', 'super_admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_events (
  id bigint generated always as identity primary key,
  event_type text not null default 'page_view' check (event_type = 'page_view'),
  page_path text not null check (char_length(page_path) between 1 and 200),
  session_id uuid not null,
  poem_id integer references public.poems(id) on delete set null,
  referrer_host text,
  device_type text not null check (device_type in ('desktop', 'tablet', 'mobile')),
  created_at timestamptz not null default now()
);
create index if not exists visitor_events_created_idx on public.visitor_events(created_at desc);
create index if not exists visitor_events_session_created_idx on public.visitor_events(session_id, created_at desc);
create index if not exists visitor_events_poem_created_idx on public.visitor_events(poem_id, created_at desc);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists(select 1 from public.admin_users where user_id = auth.uid()) $$;

alter table public.poems enable row level security;
alter table public.admin_users enable row level security;
alter table public.visitor_events enable row level security;

drop policy if exists "public read published poems" on public.poems;
create policy "public read published poems" on public.poems for select
using (is_published = true);
drop policy if exists "admins manage poems" on public.poems;
create policy "admins manage poems" on public.poems for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins read own membership" on public.admin_users;
create policy "admins read own membership" on public.admin_users for select
using (user_id = auth.uid());

alter table public.user_profiles enable row level security;
alter table public.favorites enable row level security;
drop policy if exists "users read own profile" on public.user_profiles;
create policy "users read own profile" on public.user_profiles for select using (id = auth.uid());
drop policy if exists "users update own profile" on public.user_profiles;
create policy "users update own profile" on public.user_profiles for update using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "users read own favorites" on public.favorites;
create policy "users read own favorites" on public.favorites for select using (user_id = auth.uid());
drop policy if exists "users add own favorites" on public.favorites;
create policy "users add own favorites" on public.favorites for insert with check (user_id = auth.uid());
drop policy if exists "users remove own favorites" on public.favorites;
create policy "users remove own favorites" on public.favorites for delete using (user_id = auth.uid());
create or replace function public.track_visitor_event(
  p_session_id uuid, p_path text, p_poem_id integer default null,
  p_referrer_host text default null, p_device_type text default 'desktop'
) returns void language plpgsql security definer set search_path = '' as $$
begin
  if p_session_id is null or p_path is null or left(p_path, 1) <> '/' then
    raise exception 'invalid analytics payload';
  end if;
  if p_device_type not in ('desktop', 'tablet', 'mobile') then
    raise exception 'invalid device type';
  end if;
  insert into public.visitor_events(event_type, page_path, session_id, poem_id, referrer_host, device_type)
  values ('page_view', left(p_path, 200), p_session_id, p_poem_id,
    left(nullif(p_referrer_host, ''), 120), p_device_type);
end $$;

create or replace function public.get_admin_dashboard(p_days integer default 7)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_days integer := greatest(1, least(coalesce(p_days, 7), 365)); v_result jsonb;
begin
  if not public.is_admin() then raise exception 'permission denied'; end if;
  select jsonb_build_object(
    'pv', count(*),
    'uv', count(distinct session_id),
    'today_pv', count(*) filter (where created_at >= current_date),
    'today_uv', count(distinct session_id) filter (where created_at >= current_date),
    'hot_poems', coalesce((select jsonb_agg(x order by (x->>'views')::int desc) from (
      select jsonb_build_object('id', p.id, 'title', p.title, 'views', count(*), 'count', count(*)) x
      from public.visitor_events e join public.poems p on p.id=e.poem_id
      where e.created_at >= now() - make_interval(days => v_days)
      group by p.id, p.title order by count(*) desc limit 10) q), '[]'::jsonb),
    'sources', coalesce((select jsonb_agg(x order by (x->>'count')::int desc) from (
      select jsonb_build_object('name', coalesce(nullif(referrer_host,''),'direct'), 'count', count(*)) x
      from public.visitor_events where created_at >= now() - make_interval(days => v_days)
      group by coalesce(nullif(referrer_host,''),'direct') order by count(*) desc limit 12) q), '[]'::jsonb),
    'devices', coalesce((select jsonb_agg(x order by (x->>'count')::int desc) from (
      select jsonb_build_object('name', device_type, 'count', count(*)) x
      from public.visitor_events where created_at >= now() - make_interval(days => v_days)
      group by device_type order by count(*) desc) q), '[]'::jsonb)
  ) into v_result
  from public.visitor_events where created_at >= now() - make_interval(days => v_days);
  return v_result;
end $$;

create or replace function public.get_admin_timeseries(p_days integer default 7)
returns table(day date, pv bigint, uv bigint) language plpgsql security definer set search_path = '' as $$
declare v_days integer := greatest(1, least(coalesce(p_days, 7), 365));
begin
  if not public.is_admin() then raise exception 'permission denied'; end if;
  return query select d::date, count(e.id), count(distinct e.session_id)
  from generate_series(current_date - (v_days - 1), current_date, interval '1 day') d
  left join public.visitor_events e on e.created_at >= d and e.created_at < d + interval '1 day'
  group by d order by d;
end $$;

revoke all on public.admin_users, public.visitor_events from anon, authenticated;
grant select on public.admin_users to authenticated;
grant select on public.poems to anon, authenticated;
grant select, update on public.user_profiles to authenticated;
grant select, insert, delete on public.favorites to authenticated;
grant insert, update, delete on public.poems to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.track_visitor_event(uuid,text,integer,text,text) to anon, authenticated;
grant execute on function public.get_admin_dashboard(integer) to authenticated;
grant execute on function public.get_admin_timeseries(integer) to authenticated;

-- 首位管理员需在 SQL Editor 执行：
-- insert into public.admin_users(user_id, role) values ('AUTH_USER_UUID', 'super_admin');